---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-drive-ui-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-drive-ui-controller
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - list
      - watch
  - apiGroups:
      - contour.heptio.com
    resources:
      - ingressroutes
      - tlscertificatedelegations
    verbs:
      - create
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-drive-ui-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spark-drive-ui-controller
subjects:
  - kind: ServiceAccount
    name: spark-drive-ui-controller
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-drive-ui-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: spark-drive-ui-controller
      task: tool
  template:
    metadata:
      labels:
        task: tool
        k8s-app: spark-drive-ui-controller
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      nodeSelector:
        lifecycle: OnDemand
      serviceAccount: spark-drive-ui-controller
      containers:
        - name: spark-drive-ui-controller
          image: cocoss/spark-ui-controller-envoy:0.0.4
          imagePullPolicy: Always
          args:
            - -hostsuffix
            - '.spark-ui.ushareit.me'
